export const contact = {
  numberphone: "0933194737",
  email: "chuthihien121991@gmail.com",
  address: "tổ 18,khu phố tân mai,phước tân,biên hòa",
  name: "Nguyễn Duy Hải",
  nameTitle: "XE GRAB GIÁ RẺ",
  website: "datxenhanh999.pro.vn",
  gID: "AW-16507992622",
  tokenTelegram: "7730097672:AAFPmhfkhgqp-IZCzdmenXbMUMLqWOXYUv8",
  idTelegram: "-4554340614",
};
export const posts = [
  {
    id: 2,
    title: "Đặt Xe Grab Đồng Nai",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 3,
    title: "Đặt Xe Grab Biên Hòa Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 4,
    title: "Đặt Xe Grab Vĩnh Cửu Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-vinh-cuu",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 5,
    title: "Đặt Xe Grab Long Thành Đồng Nai",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-long-thanh",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 6,
    title: "Đặt Xe Grab Nhơn Trạch Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-nhon-trach",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 7,
    title: "Đặt Xe Grab Trảng Bom Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-trang-bom",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 1,
    title: "Đặt Xe Grab Long Khánh Đồng Nai",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-long-khanh",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 8,
    title: "Đặt Xe Grab Xuân Lộc Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-xuan-loc",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 9,
    title: "Đặt Xe Grab Cẩm Mỹ Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-cam-my",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 10,
    title: "Đặt Xe Grab Thống Nhất Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-thong-nhat",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 11,
    title: "Đặt Xe Grab Định Quán Đồng Nai ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-dinh-quan",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 12,
    title: "Đặt Xe Grab Long Bình Biên Hòa ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa/grab-long-binh",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 13,
    title: "Đặt Xe Grab An Bình Biên Hòa ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa/grab-an-binh",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 14,
    title: "Đặt Xe Grab Trảng Dài Biên Hòa ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa/grab-trang-dai",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 14,
    title: "Đặt Xe Grab Đắk Lắk",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dak-lak",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 15,
    title: "Đặt Xe Grab An Giang",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-an-giang",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 15,
    title: "Đặt Xe Grab Hà Nội",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-ha-noi",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 15,
    title: "Đặt Xe Grab Thanh Hóa",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-thanh-hoa",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 15,
    title: "Đặt Xe Grab Hải Phòng",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-hai-phong",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 16,
    title: "Đặt Xe Grab Long An",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-long-an",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 17,
    title: "Đặt Xe Grab Bình Dương",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-binh-duong",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 18,
    title: "Đặt Xe Grab Bình Thuận",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-binh-thuan",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 19,
    title: "Đặt Xe Grab Tiền Giang",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-tien-giang",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 20,
    title: "Đặt Xe Grab Tây Ninh",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-tay-ninh",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 21,
    title: "Đặt Xe Grab Kiên Giang",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-kien-giang",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 22,
    title: "Đặt Xe Grab Cần Thơ",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-can-tho",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 23,
    title: "Đặt Xe Grab Bình Phước",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-binh-phuoc",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 24,
    title: "Đặt Xe Grab Bến Tre",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-ben-tre",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 25,
    title: "Đặt Xe Grab Bạc Liêu",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-bac-lieu",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 26,
    title: "Đặt Xe Grab Bà Rịa Vũng Tàu",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-ba-ria-vung-tau",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 27,
    title: "Đặt Xe Grab Hố Nai Biên Hòa",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa/grab-ho-nai",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 28,
    title: "Đặt Xe Grab Tam Hiệp Biên Hòa",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa/grab-tam-hiep",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 29,
    title: "Đặt Xe Grab Phước Tân Biên Hòa",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/grab-bien-hoa/grab-phuoc-tan",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 30,
    title:
      "Số Điện Thoại Grab Tại Biên Hoà - Hướng Dẫn Đặt Grab Biên Hoà Qua Website",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-dong-nai/so-dien-thoai-grab-bien-hoa",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 31,
    title: "Hướng Dẫn Đặt Grab Qua Website",
    link: "https://datxenhanh-24h.pro.vn/blogs/grab-xe-om-taxi-gan-day",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 32,
    title:
      "Số Điện Thoại Grab Tại Đức Hòa - Hướng Dẫn Đặt Grab Đức Hòa Qua Website",
    link: "https://datxenhanh-24h.pro.vn/blogs/xe-grab-long-an/grab-duc-hoa-long-an",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
  {
    id: 33,
    title:
      "Số Điện Thoại Grab Tại Bên Lức- Hướng Dẫn Đặt Grab Bên Lức Qua Website",
    link: "https://datxenhanh-24h.pro.vn/blogs/xe-grab-long-an/grab-ben-luc-long-an",
    img: "https://datxenhanh-24h.pro.vn/assets/image/grab.jpg",
  },
];
